"""check drift

Revision ID: 1297b15a5d27
Revises: f6a1b2c3d4e5
Create Date: 2026-09-28 21:00:07.281664
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1297b15a5d27'
down_revision: str | None = 'f6a1b2c3d4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='LEGACY: kept for backward compatibility during M2.2. Authorization MUST use tenant_memberships.role.',
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=16),
               comment='LEGACY: kept for backward compatibility during M2.2. Authorization MUST use tenant_memberships.role.',
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::character varying"))
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    # ### end Alembic commands ###
